name: CI Workflow

on:
  push: 
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest 
    container: python:3.9-slim
  build: 
    runs-on: ubuntu-latest
  